DROP TABLE IF EXISTS `book_type`;
DROP TABLE IF EXISTS `type`;
DROP TABLE IF EXISTS `book`;
DROP TABLE IF EXISTS `author`;
DROP TABLE IF EXISTS `status`;
DROP TABLE IF EXISTS `user`;

DROP TABLE IF EXISTS `setup`;
 